<?php

namespace App\Console\Commands;

use App\Support\CommerceTestDataBackupPlan;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use RuntimeException;
use Throwable;

final class BackupTestCommerceData extends Command
{
    protected $signature = 'commerce:backup-test-data-reset
        {--path= : Absolute SQL Server backup path generated by the reset workflow}
        {--database=isc : Expected SQL Server database name}';

    protected $description = 'Create and verify the guarded pre-reset SQL Server backup using the active application connection';

    public function handle(): int
    {
        if (DB::connection()->getDriverName() !== 'sqlsrv') {
            $this->error('Refusing to run: this guarded backup supports SQL Server only.');

            return self::FAILURE;
        }

        $database = (string) DB::connection()->getDatabaseName();
        $expectedDatabase = trim((string) $this->option('database'));

        if (
            $expectedDatabase === ''
            || ! hash_equals('isc', strtolower($expectedDatabase))
            || ! hash_equals(strtolower($expectedDatabase), strtolower($database))
        ) {
            $this->error("Refusing to run: connected database '{$database}' does not match the required isc database.");

            return self::FAILURE;
        }

        $path = trim((string) $this->option('path'));
        if (! CommerceTestDataBackupPlan::isAllowedPath($path)) {
            $this->error('Refusing to run: --path does not match the guarded pre-reset backup path format.');

            return self::FAILURE;
        }

        $backup = "BACKUP DATABASE [isc] TO DISK = N'{$path}' WITH COPY_ONLY, INIT, NO_COMPRESSION, CHECKSUM, STATS = 10";
        $verify = "RESTORE VERIFYONLY FROM DISK = N'{$path}' WITH CHECKSUM";

        try {
            $this->executeSql($backup);
            $this->executeSql($verify);
        } catch (Throwable $exception) {
            report($exception);
            $this->error('Backup or RESTORE VERIFYONLY failed. The reset must not proceed: '.$exception->getMessage());

            return self::FAILURE;
        }

        $this->info('COPY_ONLY backup and RESTORE VERIFYONLY completed successfully: '.$path);

        return self::SUCCESS;
    }

    private function executeSql(string $sql): void
    {
        $statement = DB::connection()->getPdo()->prepare($sql);
        if ($statement === false) {
            throw new RuntimeException('SQL Server did not prepare the backup verification statement.');
        }

        $failure = null;

        try {
            if (! $statement->execute()) {
                throw new RuntimeException('SQL Server did not execute the backup verification statement.');
            }

            do {
                if ($statement->columnCount() > 0) {
                    while ($statement->fetch() !== false) {
                        // Drain every result so PDO_SQLSRV surfaces late errors.
                    }
                }
            } while ($statement->nextRowset());
        } catch (Throwable $exception) {
            $failure = $exception;
        }

        try {
            if (! $statement->closeCursor()) {
                throw new RuntimeException('SQL Server did not release the completed backup statement.');
            }
        } catch (Throwable $cleanupException) {
            if ($failure === null) {
                $failure = $cleanupException;
            } else {
                report($cleanupException);
            }
        }

        if ($failure !== null) {
            throw $failure;
        }
    }
}
