<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductsSubDepartmentsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('Products_Sub_Department_T')->insert([
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000001',
                'Products_Departments_Id' => 1,
                'Sub_Department_Name' => 'test 2',
                'Sub_Department_Name_Ar' => 'test 2',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/PvN4T8zRIR2Cds2odOPHLtKcrNk4XgZjpixAimPI.jpg',
                'Image_Size' => 39357,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-15 09:09:13.197'),
                'updated_at' => Carbon::parse('2025-07-15 09:09:13.197'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000002',
                'Products_Departments_Id' => 8,
                'Sub_Department_Name' => 'Ball Bearings',
                'Sub_Department_Name_Ar' => 'Ball Bearings',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/MjpcNiysPV1tbYOnaVpUPhXfeVmoScJkIFcdfIZS.jpg',
                'Image_Size' => 18317,
                'Image_Extension' => 'jpeg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-16 14:14:17.223'),
                'updated_at' => Carbon::parse('2025-07-16 14:14:17.223'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000003',
                'Products_Departments_Id' => 8,
                'Sub_Department_Name' => 'Roller Bearings',
                'Sub_Department_Name_Ar' => 'Roller Bearings',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/PP85jdsVWFCB1TmAwqvpDWqAnDBF2b2UWY2lM9pC.jpg',
                'Image_Size' => 26537,
                'Image_Extension' => 'jpeg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-16 14:16:04.837'),
                'updated_at' => Carbon::parse('2025-07-16 14:16:04.837'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000004',
                'Products_Departments_Id' => 8,
                'Sub_Department_Name' => 'Thruster Bearings',
                'Sub_Department_Name_Ar' => 'Thruster Bearings',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/9Cj3MYdV7lzic4SK7KYgrqol45oR8Kx1AK5pVzI8.jpg',
                'Image_Size' => 15297,
                'Image_Extension' => 'jpeg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-16 14:18:28.620'),
                'updated_at' => Carbon::parse('2025-07-16 14:18:28.620'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000005',
                'Products_Departments_Id' => 8,
                'Sub_Department_Name' => 'Pillow Blocks Bearings',
                'Sub_Department_Name_Ar' => 'Pillow Blocks Bearings',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/LiLIeeGPydIdEWKNfaTUjKZEjC7CZMnc0pL8WZkC.png',
                'Image_Size' => 369999,
                'Image_Extension' => 'png',
                'Image_Type' => 'image/png',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-16 14:19:21.683'),
                'updated_at' => Carbon::parse('2025-07-16 14:19:21.683'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000006',
                'Products_Departments_Id' => 4,
                'Sub_Department_Name' => 'Async Motors',
                'Sub_Department_Name_Ar' => 'Async Motors',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/IGhUyfnR6GyxAyiot7cLZ79JPOTFNCiA0ack6Tqk.jpg',
                'Image_Size' => 8408,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 09:50:00.597'),
                'updated_at' => Carbon::parse('2025-07-17 09:50:00.597'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000007',
                'Products_Departments_Id' => 4,
                'Sub_Department_Name' => 'Stepper Motors',
                'Sub_Department_Name_Ar' => 'Stepper Motors',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/MmGaf7YE0ZocjyxzvSDhh3KcLez4lc4xhJgosgGP.jpg',
                'Image_Size' => 5779,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 09:50:26.073'),
                'updated_at' => Carbon::parse('2025-07-17 09:50:26.073'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000008',
                'Products_Departments_Id' => 4,
                'Sub_Department_Name' => 'Servo Motors',
                'Sub_Department_Name_Ar' => 'Servo Motors',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/I5HHDxDr24pRwcsxhrWrjnnN5tnUOZDQ4EJrXt8X.jpg',
                'Image_Size' => 6803,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 09:50:58.770'),
                'updated_at' => Carbon::parse('2025-07-17 09:50:58.770'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000009',
                'Products_Departments_Id' => 4,
                'Sub_Department_Name' => 'DC Motors',
                'Sub_Department_Name_Ar' => 'DC Motors',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/MykBx6CWZ6mFiVKS1iqrkFFNcxmlBCH38Gi6BWKU.jpg',
                'Image_Size' => 5132,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 09:51:16.287'),
                'updated_at' => Carbon::parse('2025-07-17 09:51:16.287'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000010',
                'Products_Departments_Id' => 2,
                'Sub_Department_Name' => 'Hydraulic Hoses',
                'Sub_Department_Name_Ar' => 'Hydraulic Hoses',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/ZKHkq55kCzYBOKDIGQN2CmJlt6Hm1Wzoqi0BPXud.jpg',
                'Image_Size' => 7260,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 21:26:36.053'),
                'updated_at' => Carbon::parse('2025-07-17 21:26:36.053'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000011',
                'Products_Departments_Id' => 2,
                'Sub_Department_Name' => 'Hydraulic Hose Fittings',
                'Sub_Department_Name_Ar' => 'Hydraulic Hose Fittings',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/Jfa8JJP75S7EZxG5YtRGI4jCIlvo2kL7antuZYTz.jpg',
                'Image_Size' => 6553,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 21:35:39.680'),
                'updated_at' => Carbon::parse('2025-07-17 21:35:39.680'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000012',
                'Products_Departments_Id' => 2,
                'Sub_Department_Name' => 'Hydraulic Quick Couplers',
                'Sub_Department_Name_Ar' => 'Hydraulic Quick Couplers',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/MWPlIMyP5oj57uC4rYdo1rZCpdpZlhDk2pYUiOMR.jpg',
                'Image_Size' => 6562,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 21:36:23.283'),
                'updated_at' => Carbon::parse('2025-07-17 21:36:23.283'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000013',
                'Products_Departments_Id' => 2,
                'Sub_Department_Name' => 'Hydraulic Pumps',
                'Sub_Department_Name_Ar' => 'Hydraulic Pumps',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/ELMkSBfi7krVqLU1zdsNerKug2xKcwhf0ynQIWeY.jpg',
                'Image_Size' => 6889,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 21:48:24.490'),
                'updated_at' => Carbon::parse('2025-07-17 21:48:24.490'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000014',
                'Products_Departments_Id' => 2,
                'Sub_Department_Name' => 'Hydraulic Motors',
                'Sub_Department_Name_Ar' => 'Hydraulic Motors',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/LkXhoHGmhaEc0eAz3WWnxmDOWbW7ruq2mH2yYkuF.jpg',
                'Image_Size' => 5336,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 21:49:13.827'),
                'updated_at' => Carbon::parse('2025-07-17 21:49:13.827'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000015',
                'Products_Departments_Id' => 6,
                'Sub_Department_Name' => 'Electrical Contactors',
                'Sub_Department_Name_Ar' => 'Electrical Contactors',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/R9vsD0JfWzPS6H5GFUUPHeubQDruqYGi29arwtNy.jpg',
                'Image_Size' => 7669,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 22:14:13.550'),
                'updated_at' => Carbon::parse('2025-07-17 22:14:13.550'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000016',
                'Products_Departments_Id' => 6,
                'Sub_Department_Name' => 'Electrical Breakers',
                'Sub_Department_Name_Ar' => 'Electrical Breakers',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/M9dPOt9GRHv2oWZfFjRBiCmNIPd9E5OBSs1gM5VZ.jpg',
                'Image_Size' => 9045,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 22:15:07.307'),
                'updated_at' => Carbon::parse('2025-07-17 22:15:07.307'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000017',
                'Products_Departments_Id' => 6,
                'Sub_Department_Name' => 'Motor Starters',
                'Sub_Department_Name_Ar' => 'Motor Starters',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/QkqyeExxO4C0kKTOpjsRtwgGTNiqiBRo4HUzS5wq.jpg',
                'Image_Size' => 4401,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 22:16:27.253'),
                'updated_at' => Carbon::parse('2025-07-17 22:16:27.253'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000018',
                'Products_Departments_Id' => 6,
                'Sub_Department_Name' => 'Motor Overload Protection',
                'Sub_Department_Name_Ar' => 'Motor Overload Protection',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/xFZghvbWObh7a3qHZNzNbwzgrAR5gHvOAfrru5Uz.jpg',
                'Image_Size' => 9669,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-17 22:17:04.180'),
                'updated_at' => Carbon::parse('2025-07-17 22:17:04.180'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000019',
                'Products_Departments_Id' => 5,
                'Sub_Department_Name' => 'Manual Tools',
                'Sub_Department_Name_Ar' => 'Manual Tools',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/b7dX5rvs2euwQTqjxaulek6r2KAiZzUl7kEM8lTf.jpg',
                'Image_Size' => 4810,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 20:52:50.980'),
                'updated_at' => Carbon::parse('2025-07-19 20:52:50.980'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000020',
                'Products_Departments_Id' => 5,
                'Sub_Department_Name' => 'Power Tools',
                'Sub_Department_Name_Ar' => 'Power Tools',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/BxQBSG1ebeltzpVe0jf2etueidO6K2PHsYJitlmR.jpg',
                'Image_Size' => 12667,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 20:57:10.003'),
                'updated_at' => Carbon::parse('2025-07-19 20:57:10.003'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000021',
                'Products_Departments_Id' => 7,
                'Sub_Department_Name' => 'Electrical Low Voltage Cables',
                'Sub_Department_Name_Ar' => 'Electrical Low Voltage Cables',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/jWiuE8StpXhAwQAywgrdKjapVT0mk2XlYyDMGm7A.jpg',
                'Image_Size' => 6321,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:04:46.643'),
                'updated_at' => Carbon::parse('2025-07-19 22:04:46.643'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000022',
                'Products_Departments_Id' => 7,
                'Sub_Department_Name' => 'Electrical Medium Voltage Cables',
                'Sub_Department_Name_Ar' => 'Electrical Medium Voltage Cables',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/XQEkEqyTD1jEfUun3Ts2e4pdZ4k6CtHV3wyAC8iC.jpg',
                'Image_Size' => 9171,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:05:25.987'),
                'updated_at' => Carbon::parse('2025-07-19 22:05:25.987'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000023',
                'Products_Departments_Id' => 7,
                'Sub_Department_Name' => 'Electrical High Voltage Cables',
                'Sub_Department_Name_Ar' => 'Electrical High Voltage Cables',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/zL82T38tK0sIDdVp2MXpGWCWoAaDeDmxs4ctLYkP.jpg',
                'Image_Size' => 10107,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:06:07.297'),
                'updated_at' => Carbon::parse('2025-07-19 22:06:07.297'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000024',
                'Products_Departments_Id' => 3,
                'Sub_Department_Name' => 'Pneumatic Hoses',
                'Sub_Department_Name_Ar' => 'Pneumatic Hoses',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/Acd696s1Q0DL9nLgKpkLwLE9qXXqIUpiENdeuNx6.jpg',
                'Image_Size' => 7036,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:33:07.807'),
                'updated_at' => Carbon::parse('2025-07-19 22:33:07.807'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000025',
                'Products_Departments_Id' => 3,
                'Sub_Department_Name' => 'Pneumatic Fittings',
                'Sub_Department_Name_Ar' => 'Pneumatic Fittings',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/uyejLNSwc3UqltPGP0dDQOaeYKPnkJX7oKlSGGFQ.jpg',
                'Image_Size' => 9846,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:33:53.143'),
                'updated_at' => Carbon::parse('2025-07-19 22:33:53.143'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000026',
                'Products_Departments_Id' => 3,
                'Sub_Department_Name' => 'Pneumatic Valves',
                'Sub_Department_Name_Ar' => 'Pneumatic Valves',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/IJj0CWSPUSEdi0msGClK4k6F4kdY5obIZrOUjx4B.jpg',
                'Image_Size' => 6373,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:34:41.660'),
                'updated_at' => Carbon::parse('2025-07-19 22:34:41.660'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000027',
                'Products_Departments_Id' => 3,
                'Sub_Department_Name' => 'Pneumatic Air Filter-Regulators',
                'Sub_Department_Name_Ar' => 'Pneumatic Air Filter-Regulators',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/LSn7qPGhFC5pZvbFwU28j861tdXp2LCO86QtXdDG.jpg',
                'Image_Size' => 6145,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:35:35.303'),
                'updated_at' => Carbon::parse('2025-07-19 22:35:35.303'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000028',
                'Products_Departments_Id' => 3,
                'Sub_Department_Name' => 'Pneumatic Jacks',
                'Sub_Department_Name_Ar' => 'Pneumatic Jacks',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/1bp3HbqZlteTeMXGc6KyuWQz9745q2U0GtHdNOcB.jpg',
                'Image_Size' => 4377,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:37:10.557'),
                'updated_at' => Carbon::parse('2025-07-19 22:37:10.557'),
            ],
            [
                'Products_Sub_Department_Code' => 'SUBDEPT_2025_JUL_A_000029',
                'Products_Departments_Id' => 3,
                'Sub_Department_Name' => 'Pneumatic Switches',
                'Sub_Department_Name_Ar' => 'Pneumatic Switches',
                'Sub_Department_Description' => null,
                'Image_path' => 'subdepartment/3EljDdSwmaOkRyEYlbZ8GrX4GERcPYeg9zt30EPC.jpg',
                'Image_Size' => 6019,
                'Image_Extension' => 'jpg',
                'Image_Type' => 'image/jpeg',
                'Created_By' => 1,
                'created_at' => Carbon::parse('2025-07-19 22:43:01.537'),
                'updated_at' => Carbon::parse('2025-07-19 22:43:01.537'),
            ],
            
        ]);
    }
}